version: "3"
services:
  backend:
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - neo4j_db
    environment:
      - NEO4J_BOLT_URL=bolt://neo4j:espectateurneo4j@neo4j_db:11007/espneo4j
      - DJANGO_SETTINGS_MODULE=myproject.settings
  neo4j_db:
    image: neo4j:4.4.0-enterprise
    ports:
      - 11008:7474
      - 11007:7687
    expose:
      - 7474
      - 7687
    volumes:
      - db:/data/dbms
      - ./dump:/dump
    environment:
      - NEO4J_AUTH=neo4j/espectateurneo4j
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - dbms.connector.bolt.listen_address=:7687
      - dbms.connector.bolt.advertised_address=:7473
      - NEO4JLABS_PLUGINS=["apoc", "n10s"]
      - dbms.allow_upgrade=true
volumes:
  db:
  